### PR TITLE
new UI to accommodate different shapes

### PR DESCRIPTION
**Pull request by rupl**
I would love to implement [fluid touch gestures](http://www.lukew.com/ff/entry.asp?1932)
1. touch a shape
2. drag out for the size
3. drag side-to-side for hue

swipe up/down on existing shapes to change opacity

### CODE REVIEW

**Comment by afragon** [comment]
An idea would be to add a set color palette with 10 colors for color-coding workshops.
- yellow, green, blue, red, orange, light blue, brown, pink, purple, light green.

**Comment by rupl** [comment]
What about a color wheel like this? http://codepen.io/g12n/pen/YXEMyQ?editors=110

**Comment by rupl** [comment]
whew so I kind of went off into the woods trying to lay the work for this. The sign-on will be cleaned up and in general the UI will get a complete overhaul :confetti_ball:

**Comment by rupl** [comment]
ok this sat long enough I need to :shipit: and finish the rest later

**Comment by rupl** [comment]
@afragon you have circles now \o/

**Pull request merged**
