### PR TITLE
New shapes should be relative to current state of canvas

### PR DESCRIPTION
**Pull request by rupl**
I noticed as I tested #24 that after zooming out a few times and making progressively bigger shapes, the new ones were too tiny to grab with two fingers to scale up. The new shapes should always be roughly the same size on your screen, and perhaps they should always appear in the top-left corner.

I _think_ this is as simple as checking canvas scale/translation when creating new shape, and offsetting by those amounts. But I've been known to oversimplify math before :grin:

### CODE REVIEW

**Comment by rupl** [comment]
I set a zoom limit because after getting relatively sized shapes working, I frequently "fell off" the canvas, which we see folks doing frequently when they zoom out so far (approx 1/1000x) the rounding errors cause everything to disappear. The limit is at 1000 because it seems to be the threshold where things disappear.

**Comment by rupl** [comment]
awww yeah, this works great on my end. @afragon could you try going to https://bustashape-pr-32.herokuapp.com/ and tell me what you think?
- popping restored
- new shapes should be in the center of the screen and same size always
- zooming in/out should eventually cut off at a certain point — specifically, that moment when you zoom too far out and everything disappears should no longer happen at all.

**Comment by afragon** [comment]
Works perfect!!! Good job! Love the effect!!

**Pull request merged**
