### PR TITLE
Playback support. Fixes #9.

### LINKED ISSUE #9: Playback a room
With #7 and #8 in place it would be awesome to watch a room get built as if you were watching it in real-time. Like watching this: https://www.youtube.com/watch?v=ztwSAZ7lJg8

### PR DESCRIPTION
**Pull request by rupl**
Opening a PR based on @mattgrill's fine work.

I think we need to hide some of this behind a config flag so we can easily control how/when it's used. I also need to make sure Heroku is set up right before deploying this.
- Scenario 1: "instant mode" would bring a user to the current state of things immediately upon login. Ideally we'd poll Redis and just grab the last known state of each shape. All shapes are instantly interactive as if the person has been there all along.
- Scenario 2: "observer mode" would play it back in real-time. The user would not be able to grab stuff until we reach the end. This mode isn't built yet but the data is theoretically being collected when this PR is merged.

### CODE REVIEW

**Comment by rupl** [comment]
what I described as "instant mode" would be the key to making a gallery as @afragon described in #18

**Comment by mattgrill** [comment]
@rupl I'll fix these conflicts.

**Comment by rupl** [comment]
@mattgrill my hero :two_hearts:

**Comment by rupl** [comment]
for now I am closing this. I have been brainstorming how to make this decentralized and I think I'd rather do that. No idea if I can pull it off but I will try!

**Pull request closed without merging**
