### PR TITLE
use two.js for manipulating shapes

### PR DESCRIPTION
**Pull request by rupl**
> Two.js is a two-dimensional drawing api geared towards modern web browsers. It is renderer agnostic enabling the same api to draw in multiple contexts: svg, canvas, and webgl.

http://jonobr1.github.io/two.js/

Would help solve #3, #4, #13, #15

### CODE REVIEW

**Comment by rupl** [comment]
This is starting to come along!! I have no idea if I am accomplishing it in a smart way, but it still works on my iPhone and MacBook when I test. I used [SVG](http://caniuse.com/#feat=svg) mode, because [WebGL](http://caniuse.com/#feat=webgl) will still exclude too many mobile users.

**Comment by rupl** [comment]
damn.. I think I nailed this in one night!

@afragon are you planning on using the site for anything public in the next week? I don't want to ship this if something is coming up, so I can have a few days to debug any problems that it might have introduced.

**Comment by rupl** [comment]
ok the only thing that we lost is the little popping animation when you create a shape. I'm sure I can somehow re-do that within two.js but the existing CSS animation was not playing well with the new library. ¯\_(ツ)_/¯

**Comment by afragon** [comment]
@rupl No there won't be any public events during next week

**Comment by rupl** [comment]
:+1: ok then merging and I'll file any issues as follow-ups. give it a shot!

**Pull request merged**
