### PR TITLE
Bottom drawer (like iOS) for shape options

### PR DESCRIPTION
**Pull request by rupl**
Just like the global iOS settings, dragging on a shape reveals options. simple taps still create the shape

### CODE REVIEW

**Comment by rupl** [comment]
@afragon this could really use a test before going out. I'm sure there will be kinks so please try it out and if something is weird just post here and let me know.

https://bustashape-pr-68.herokuapp.com/

**Comment by rupl** [comment]
After testing a bit, it will take another pass to improve color picking on iOS before I'm comfortable shipping this.

**Comment by rupl** [comment]
man what a drag. Still trying to find a color picker that doesn't completely suck for iOS. In the interest of making this thing tip-top, I might write my own.

**Comment by rupl** [comment]
I found a [picker with decent UX](http://david-mulder.github.io/paper-color-picker/components/paper-color-picker/demo/) (the "My Favorite color" example specifically), but I don't really want to add MD as a dep just for one widget.

**Comment by rupl** [comment]
This one is also very close to what I had in mind, but it's not touch friendly. A good place to start if it has a license we can work with: http://color.aurlien.net/

**Comment by rupl** [comment]
ok a color picker is almost a distraction to me at this point. it's a hard problem and I really want this drawer there so we can use the parts that work.

I think I will assemble a list of color palettes and start populating one randomly on page load instead of the hardcoded palette we have at the moment. Then at least we get some variety while I sort out the color picker.

**Comment by afragon** [comment]
Use colorhunt for findung different palettes.

tisdag 11 oktober 2016 skrev Chris Ruppel notifications@github.com:

**Comment by rupl** [comment]
yup I grabbed 10 random ones. gonna swap a few out because some contain colors which are too light for a white background. I'll just avoid them for now.

**Comment by rupl** [comment]
@afragon if you can, give this a test https://bustashape-pr-68.herokuapp.com/

I have tested it to the best of my ability but I've got some developer blindness at the moment, just try and break it if you can!

**Comment by rupl** [comment]
oh also when I added random palettes I realized two users joining one room would most likely have different colors, so I added the ability to sync those too!

**Comment by rupl** [comment]
welp. :shipit:

**Comment by rupl** [comment]
man, super glad to put that one (mostly) to rest. I started work on this one during Vetfest!

**Pull request merged**
